default: false
servicios:
  background: /img/51cb4e17-9911-4246-8d64-643622841fc6.jpg
  text: Servicios | Proyectos
capacitacion:
  background: /img/293de21e-0857-4ea3-b9c0-ed944051d876.jpg
  text: Cursos | Talleres
trabajo:
  background: /img/13a7410e-2ef3-43bd-8531-53b834ee0c0a.jpg
  text: >-
    Aquí puede ofertar sus servicios laborales tanto para empresas como para
    particulares y si es una empresa puede solicitar personal desde pasantes
    hasta profesionales en todos los niveles , interactúa en nuestra plataforma
    laboral de Megatron.
contacto:
  address:
    text: 'Av. Cañoto \# 113 esq. Buenos Aires | Santa Cruz | Bolivia'
    url: >-
      https://www.google.com/maps/place/Megatron+Empresa+Industrial/@-17.7814131,-63.1908203,17z/data=!3m1!4b1!4m5!3m4!1s0x93f1e9cd70711897:0x7a8e9bc0f6959a56!8m2!3d-17.7814182!4d-63.1886316
    visible: true
  email:
    value: ing_fvargas@hotmail.com
    visible: true
  facebook:
    url: 'https://www.facebook.com/Megatron-1457765754508825/'
    visible: true
  info:
    - description: >-
        Somos una empresa dinámica y distinta dedicada al desarrollo de
        ingeniería, investigación, capacitación y actualización características
        necesarias para avanzar en el área industrial BOLIVIANA
      title: Megatron
  tel:
    value: 3303219
    visible: true
  whatsapp:
    text: 'Hola Megatron, vengo de su sitio web'
    value: 70497120
    visible: true
  youtube:
    url: 'https://www.youtube.com/channel/UCm9e7feD8F3qrn6hFUX_aIw'
    visible: true
